baseURL = "https://trisatest.net/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "TRISA TestNet"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "Test and Integration platform for TRISA"
    github_repository = "https://github.com/trisacrypto/testnet"
    version = ""

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/trisacrypto/testnet"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Theme settings section
    dateformat = "January 2, 2006" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = []

# Global menu section
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 5

[[menu.main]]
    name = "White Paper"
    url = "https://trisa.io/trisa-whitepaper/"
    weight = 5

[markup.goldmark.renderer]
    unsafe = true