baseURL = "https://trisa.dev/"
theme = "hugo-theme-relearn"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Source Code repository section
    description = ""
    github_repository = "https://github.com/trisacrypto/trisa"
    version = "v1beta1"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/trisacrypto/trisa"

    # Analytic section
    google_analytics_id = ""      # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # When using multilingual website, disable the switch language button.
    disableLanguageSwitchingButton = false

    # Theme settings section
    # Theme color
    themeVariant = "blue"
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Theme settings section
    dateformat = "January 2, 2006" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = []

    disableInlineCopyToClipBoard = true

[Languages]
[Languages.en]
title = "TRISA Documentation"
weight = 1
languageName = "English"
landingPageName = "<i class='fas fa-home'></i> Home"

[Languages.de]
title = "TRISA Dokumentation"
weight = 2
languageName = "Deutsch"
landingPageName = "<i class='fas fa-home'></i> Startseite"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = false

